const classrooms=[
    {
        "id":0,
        "klass":"All Grades",
        "division":""
    },
    {
        "id":8640,
        "klass":"1",
        "klass_id":10,
        "division":"A",
        "school_id":27,
        "code":"EXP02701A",
        "is_active":true
    },
    {
        "id":9588,
        "klass":"2",
        "klass_id":11,
        "division":"A",
        "school_id":27,
        "code":"EXP02702A",
        "is_active":true
    },
    {
        "id":9589,
        "klass":"3",
        "klass_id":12,
        "division":"A",
        "school_id":27,
        "code":"EXP02703A",
        "is_active":true
    },
    {
        "id":9590,
        "klass":"4",
        "klass_id":13,
        "division":"A",
        "school_id":27,
        "code":"EXP02704A",
        "is_active":true
    },
    {
        "id":9591,
        "klass":"5",
        "klass_id":7,
        "division":"A",
        "school_id":27,
        "code":"EXP02705A",
        "is_active":true
    },
    {
        "id":412,
        "klass":"6",
        "klass_id":8,
        "division":"A",
        "school_id":27,
        "code":"EXP02706A",
        "is_active":true
    },
    {
        "id":413,
        "klass":"6",
        "klass_id":8,
        "division":"B",
        "school_id":27,
        "code":"EXP02706B",
        "is_active":true
    },
    {
        "id":414,
        "klass":"6",
        "klass_id":8,
        "division":"C",
        "school_id":27,
        "code":"EXP02706C",
        "is_active":true
    },
    {
        "id":415,
        "klass":"6",
        "klass_id":8,
        "division":"D",
        "school_id":27,
        "code":"EXP02706D",
        "is_active":true
    },
    {
        "id":416,
        "klass":"6",
        "klass_id":8,
        "division":"E",
        "school_id":27,
        "code":"EXP02706E",
        "is_active":true
    },
    {
        "id":417,
        "klass":"6",
        "klass_id":8,
        "division":"F",
        "school_id":27,
        "code":"EXP02706F",
        "is_active":true
    },
    {
        "id":75,
        "klass":"7",
        "klass_id":9,
        "division":"A",
        "school_id":27,
        "code":"RYAN-27-7-A",
        "is_active":true
    },
    {
        "id":76,
        "klass":"7",
        "klass_id":9,
        "division":"B",
        "school_id":27,
        "code":"RYAN-27-7-B",
        "is_active":true
    },
    {
        "id":78,
        "klass":"7",
        "klass_id":9,
        "division":"C",
        "school_id":27,
        "code":"RYAN-27-7-C",
        "is_active":true
    },
    {
        "id":79,
        "klass":"7",
        "klass_id":9,
        "division":"D",
        "school_id":27,
        "code":"RYAN-27-7-D",
        "is_active":true
    },
    {
        "id":406,
        "klass":"8",
        "klass_id":1,
        "division":"A",
        "school_id":27,
        "code":"EXP02708A",
        "is_active":true
    },
    {
        "id":407,
        "klass":"8",
        "klass_id":1,
        "division":"B",
        "school_id":27,
        "code":"EXP02708B",
        "is_active":true
    },
    {
        "id":408,
        "klass":"8",
        "klass_id":1,
        "division":"C",
        "school_id":27,
        "code":"EXP02708C",
        "is_active":true
    },
    {
        "id":409,
        "klass":"8",
        "klass_id":1,
        "division":"D",
        "school_id":27,
        "code":"EXP02708D",
        "is_active":true
    },
    {
        "id":410,
        "klass":"8",
        "klass_id":1,
        "division":"E",
        "school_id":27,
        "code":"EXP02708E",
        "is_active":true
    },
    {
        "id":411,
        "klass":"8",
        "klass_id":1,
        "division":"F",
        "school_id":27,
        "code":"EXP02708F",
        "is_active":true
    },
    {
        "id":401,
        "klass":"9",
        "klass_id":2,
        "division":"B",
        "school_id":27,
        "code":"EXP02709B",
        "is_active":true
    },
    {
        "id":402,
        "klass":"9",
        "klass_id":2,
        "division":"D",
        "school_id":27,
        "code":"EXP02709D",
        "is_active":true
    },
    {
        "id":403,
        "klass":"9",
        "klass_id":2,
        "division":"E",
        "school_id":27,
        "code":"EXP02709E",
        "is_active":true
    },
    {
        "id":404,
        "klass":"9",
        "klass_id":2,
        "division":"F",
        "school_id":27,
        "code":"EXP02709F",
        "is_active":true
    },
    {
        "id":405,
        "klass":"9",
        "klass_id":2,
        "division":"G",
        "school_id":27,
        "code":"EXP02709G",
        "is_active":true
    },
    {
        "id":71,
        "klass":"10",
        "klass_id":3,
        "division":"A",
        "school_id":27,
        "code":"RYAN-27-10-A",
        "is_active":true
    },
    {
        "id":72,
        "klass":"10",
        "klass_id":3,
        "division":"B",
        "school_id":27,
        "code":"RYAN-27-10-B",
        "is_active":true
    },
    {
        "id":73,
        "klass":"10",
        "klass_id":3,
        "division":"C",
        "school_id":27,
        "code":"RYAN-27-10-C",
        "is_active":true
    },
    {
        "id":74,
        "klass":"10",
        "klass_id":3,
        "division":"D",
        "school_id":27,
        "code":"RYAN-27-10-D",
        "is_active":true
    },
    {
        "id":418,
        "klass":"10",
        "klass_id":3,
        "division":"E",
        "school_id":27,
        "code":"EXP02710E",
        "is_active":true
    },
    {
        "id":419,
        "klass":"10",
        "klass_id":3,
        "division":"F",
        "school_id":27,
        "code":"EXP02710F",
        "is_active":true
    },
    {
        "id":420,
        "klass":"10",
        "klass_id":3,
        "division":"G",
        "school_id":27,
        "code":"EXP02710G",
        "is_active":true
    },
    {
        "id":421,
        "klass":"10",
        "klass_id":3,
        "division":"H",
        "school_id":27,
        "code":"EXP02710H",
        "is_active":true
    },
    {
        "id":9592,
        "klass":"11",
        "klass_id":4,
        "division":"A",
        "school_id":27,
        "code":"EXP02711A",
        "is_active":true
    },
    {
        "id":9593,
        "klass":"12",
        "klass_id":5,
        "division":"A",
        "school_id":27,
        "code":"EXP02712A",
        "is_active":true
    }
]
const getLable = (klass) => {
    if(klass === '1') return `${klass}st`;
    else if(klass === '2') return `${klass}nd`;
    else if(klass === '3') return `${klass}rd`;
    else return `${klass}th`;
}

let gradeOptions = [];
let gradeSectionsMap = {};
(classrooms || []).forEach((classRoom) => {
    if(classRoom.id === 0) return;
    let ele = gradeSectionsMap[classRoom.klass_id];
    let sectionOption = {
        label: `${classRoom.klass}${classRoom.division}`,
        value: classRoom.id
    }
    if(ele) {
        ele.push(sectionOption)
    } else {
        gradeSectionsMap[classRoom.klass_id] = [sectionOption]
        gradeOptions.push({
            label: getLable(classRoom.klass),
            value: classRoom.klass_id
        })
    }
})

console.log({gradeOptions})

